// examples/beta/svelte/src/App.svelte
<script lang="ts">
  import Button from "./components/button.svelte";

  const intents = ["primary", "secondary"] as const;
  const sizes = ["medium", "small"] as const;
  const isDisabled = [false, true] as const;
</script>

<table class="variant-table">
  <thead>
    <tr>
      <th />
      <th />
      {#each intents as intent}
        <th scope="col">{intent || "default"}</th>
      {/each}
    </tr>
  </thead>
  <tbody>
    {#each isDisabled as disabled}
      {#each sizes as size, index}
        <tr>
          {#if index === 0}
            <th scope="rowgroup" rowSpan={3}>
              {disabled ? "disabled" : "enabled"}
            </th>
          {/if}
          <th scope="row">{size || "default"}</th>
          {#each intents as intent}
            <td>
              <Button
                {...intent && { intent }}
                {...size && { size }}
                {...disabled && { disabled }}
              >
                {intent || "default"} button
              </Button>
            </td>
          {/each}
        </tr>
      {/each}
    {/each}
  </tbody>
</table>

<style>
  .variant-table {
    position: relative;
    height: max-content;
    width: max-content;
    align-self: center;
    justify-self: center;
  }

  .variant-table :where(th, td) {
    padding: 0.5rem;
  }
</style>

// examples/beta/vue/src/App.vue
<script setup lang="ts">
import Button from "./components/Button.vue";

const intents = ["primary", "secondary"] as const;
const sizes = ["medium", "small"] as const;
const isDisabled = [undefined, ""] as const;
</script>

<template>
  <table class="variant-table">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th v-for="intent in intents">
          {{ intent || "default" }}
        </th>
      </tr>
    </thead>
    <tbody>
      <template v-for="disabled in isDisabled">
        <tr v-for="(size, index) in sizes">
          <th v-if="index === 0" scope="rowgroup" rowspan="3">
            {{ typeof disabled === "undefined" ? "enabled" : "disabled" }}
          </th>

          <th scope="row">{{ size || "default" }}</th>

          <td v-for="intent in intents">
            <Button :disabled="disabled" :intent="intent" :size="size"
              >{{ intent || "default" }} button
            </Button>
          </td>
        </tr>
      </template>
    </tbody>
  </table>
</template>

<style scoped>
.variant-table {
  position: relative;
  height: max-content;
  width: max-content;
  align-self: center;
  justify-self: center;
}

.variant-table :where(th, td) {
  padding: 0.5rem;
}
</style>
